### ISSUE TITLE
Deprecated: Non-static method

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql-insights#9]
When I activated the plugin I got the error message below and the query in GraphiQL no longer worked either:

> Deprecated: Non-static method WPGraphQL\Extensions\Insights\Setup::register() should not be called statically in C:\wf\wordpress\wp-includes\class-wp-hook.php on line 298

I'm using PHP 7.1.9 and WordPress 4.8.2

**Comment by jasonbahl** [comment]
What version of WPGraphQL and what version of this plugin are you on?

**Comment by cr101** [comment]
WPGraphQL 0.0.22 and WPGraphQL Insights 0.0.1

**Comment by jasonbahl** [comment]
Pretty sure this has long been resolved. Closing, but feel free to open again if you're running into a similar issue.
